insert into message (text, senderid, recieverid, file, picture, date) values ('kiscica', 1, 1, NULL, NULL, '2018-10-10');
insert into message (text, senderid, recieverid, file, picture, date) values ('nem, inkabb nagycica', 2, 2, NULL, NULL, '2018-10-11');
insert into message (text, senderid, recieverid, file, picture, date) values ('ideneeeeezz', 3, 3, NULL, NULL, '2018-11-06');
insert into message (text, senderid, recieverid, file, picture, date) values ('loremipsum', 4, 4, NULL, NULL, '2018-11-02');
insert into message (text, senderid, recieverid, file, picture, date) values ('en elmentem a vasarba', 5, 5, NULL, NULL, '2018-10-20');
insert into message (text, senderid, recieverid, file, picture, date) values ('random szoveg', 6, 6, NULL, NULL, '2018-10-30');
insert into message (text, senderid, recieverid, file, picture, date) values ('meg random szoveg', 7, 7, NULL, NULL, '2018-11-05');
insert into message (text, senderid, recieverid, file, picture, date) values ('nyalas idezet helye', 8, 8, NULL, NULL, '2018-11-04');
insert into message (text, senderid, recieverid, file, picture, date) values ('yarrr', 9, 9, NULL, NULL, '2018-11-03');
insert into message (text, senderid, recieverid, file, picture, date) values ('yarrr', 10, 10, NULL, NULL, '2018-11-03');