insert into members (role, userId, groupId) values ('god', '1', '1');
insert into members (role, userId, groupId) values ('admin', '2', '2');
insert into members (role, userId, groupId) values ('guest', '3', '3');
insert into report (status, subject, solution, membersId, userId) values ('cancelled', 'thing4', 'solved', '6', '6');
insert into report (status, subject, solution, membersId, userId) values ('cancelled', 'thing4', 'deleted', '5', '5');
insert into report (status, subject, solution, membersId, userId) values ('in progress', 'thing4', 'deleted', '4', '4');
insert into report (status, subject, solution, membersId, userId) values ('opened', 'thing3', 'deleted', '3', '3');
insert into report (status, subject, solution, membersId, userId) values ('in progress', 'thing1', 'deleted', '2', '2');
insert into _group (status, description) values ('public', 'ble-ble-ble');
insert into _group (status, description) values ('hidden', 'bla-bla-bla');
